[tool.pylint.messages_control]

max-line-length = 88

disable = [
    "missing-function-docstring",
    "missing-final-newline",
    "missing-class-docstring",
    "reimported",
    "wrong-import-order",
    "wrong-import-position",
    "line-too-long",
    "unused-import",
    "ungrouped-imports",
    "invalid-name",
    "consider-using-with",
    "unused-variable",
    "redefined-outer-name",
    "consider-using-enumerate"
    ]


[tool.isort]
skip = [".gitignore", ".dockerignore"]
extend_skip=.md,.json
